services:
  - type: web
    name: booksy-backend
    env: node
    rootDir: ./backend
    buildCommand: cd ../frontend && npm install && npm run build && cd ../backend && npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production 